networks:
  socialfood-network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./frontend:/home/node/app
    networks:
      - socialfood-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    container_name: backend
    volumes:
      - ./backend:/var/www
    networks:
      - socialfood-network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4.1
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - socialfood-network

volumes:
  mysql-data:
